In [1]:
import numpy as np

In [18]:
n = 10
A = np.full([n,n], 0)
f = np.zeros(n)

In [23]:
for i in range(n-1):
    A[i+1][i+1] = -2
    A[i][i+1] = 1
    A[i+1][i] = 1
    A[n-1][i] = 2
    if i == 0:
        f[i] =1
    else:
        f[i] = 2 / i /i

A[0][0] = 1
A[0][1] = 0
A[n-1][n-1] = 1
A[n-1][0] = 1
f[n-1] = -3

A

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1, -2,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1, -2,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1, -2,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -2,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1, -2,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1, -2,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  1, -2,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1, -2,  1],
       [ 1,  2,  2,  2,  2,  2,  2,  2,  2,  1]])

In [24]:
f

array([ 1.        ,  2.        ,  0.5       ,  0.22222222,  0.125     ,
        0.08      ,  0.05555556,  0.04081633,  0.03125   , -3.        ])

In [32]:
np.linalg.eigvals(A)

array([ 1.796289  , -3.87938524, -3.55984756, -3.        , -2.4802047 ,
       -0.42688003, -0.46791111, -1.65270364, -1.32935671,  1.        ])

In [35]:
np.linalg.norm(A, 2) * np.linalg.norm(np.linalg.inv(A), 2)

40.66852489935435

Число обусловленности \mu = 40.7

In [94]:
norm_A = np.linalg.norm(np.dot(A, np.transpose(A)),2)
B = np.linalg.inv(A)
norm_B = np.linalg.norm(np.dot(np.transpose(B),B),2)
np.sqrt(norm_A*norm_B)

40.66852489935435

# Метод Зейделя

In [106]:
D = np.zeros_like(A)
L = np.zeros_like(A)
U = np.zeros_like(A)

for i in range(n):
    D[i][i] = A[i][i]
for i in range(n):
    for j in range(n):
        if i<j:
            U[i][j] = A[i][j]
        if i>j:
            L[i][j] = A[i][j]
print(D, '\n', L,'\n', U)

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0 -2  0  0  0  0  0  0  0  0]
 [ 0  0 -2  0  0  0  0  0  0  0]
 [ 0  0  0 -2  0  0  0  0  0  0]
 [ 0  0  0  0 -2  0  0  0  0  0]
 [ 0  0  0  0  0 -2  0  0  0  0]
 [ 0  0  0  0  0  0 -2  0  0  0]
 [ 0  0  0  0  0  0  0 -2  0  0]
 [ 0  0  0  0  0  0  0  0 -2  0]
 [ 0  0  0  0  0  0  0  0  0  1]] 
 [[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 2 2 2 2 2 2 2 2 0]] 
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]]


In [100]:
R = - np.dot(np.linalg.inv(D + L), U)
F = np.dot(np.linalg.inv(D + L), f)

In [104]:
x = np.zeros(n)
eps = 10e-16

e0 = np.linalg.norm(f - np.dot(A,x))
# eps1 = np.linalg.norm(sol1 - x, 2)
q = np.linalg.norm(R,2)

np.log( e0 / eps) / np.log(q)

21.9717737179236

Число итераций не сходится??

In [105]:

for i in range(140):
    x = np.dot(R, x) + F
    if i % 10 == 0 or i > 130 :
        norm = np.linalg.norm(f - np.dot(A, x), 2)
        print("step ", i, "  ", norm)
print(x)
sol1 = x

step  0    0.6969548596135919
step  10    0.06863199115952039
step  20    0.003840286299320026
step  30    0.0002159063598087948
step  40    1.2182092743871381e-05
step  50    6.904086620102315e-07
step  60    3.934101237972477e-08
step  70    2.255199095286678e-09
step  80    1.3005930465347938e-10
step  90    7.541688095402922e-12
step  100    4.4005110977609855e-13
step  110    2.6982221523041907e-14
step  120    3.3466264437256366e-15
step  130    2.8001940523528655e-15
step  131    1.838230735157046e-15
step  132    1.7975485573266372e-15
step  133    1.7863710345568807e-15
step  134    1.7811885205215376e-15
step  135    1.7837816596687952e-15
step  136    1.7837816596687952e-15
step  137    1.7837816596687952e-15
step  138    1.7837816596687952e-15
step  139    1.7837816596687952e-15
[ 1.         -1.30369772 -1.60739544 -1.41109316 -0.99256866 -0.44904415
  0.17448035  0.85356041  1.57345679  2.32460317]


# Метод Гаусса

In [65]:
def gauss(A):
    n = len(A)

    for i in range(0, n):
        # Search for maximum in this column
        maxEl = abs(A[i][i])
        maxRow = i
        for k in range(i + 1, n):
            if abs(A[k][i]) > maxEl:
                maxEl = abs(A[k][i])
                maxRow = k

        # Swap maximum row with current row (column by column)
        for k in range(i, n + 1):
            tmp = A[maxRow][k]
            A[maxRow][k] = A[i][k]
            A[i][k] = tmp

        # Make all rows below this one 0 in current column
        for k in range(i + 1, n):
            c = -A[k][i] / A[i][i]
            for j in range(i, n + 1):
                if i == j:
                    A[k][j] = 0
                else:
                    A[k][j] += c * A[i][j]

    # Solve equation Ax=b for an upper triangular matrix A
    x = [0 for i in range(n)]
    for i in range(n - 1, -1, -1):
        x[i] = A[i][n] / A[i][i]
        for k in range(i - 1, -1, -1):
            A[k][n] -= A[k][i] * x[i]
    return x

In [80]:
B = np.zeros([n, n+1])
for i in range(n):
    for j in range(n):
        B[i][j] = A[i][j]
    B[i][n] = f[i]
B

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 1.        , -2.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.        ],
       [ 0.        ,  1.        , -2.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.5       ],
       [ 0.        ,  0.        ,  1.        , -2.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.22222222],
       [ 0.        ,  0.        ,  0.        ,  1.        , -2.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.125     ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        -2.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.08 

In [81]:
sol2 = gauss(B)
sol2

[1.0,
 -1.3036977198286719,
 -1.607395439657344,
 -1.4110931594860165,
 -0.9925686570924664,
 -0.44904415469891656,
 0.1744803476946333,
 0.8535604056437388,
 1.5734567901234566,
 2.3246031746031743]

In [82]:
print(sol1 - sol2)

[ 0.00000000e+00 -2.22044605e-16 -2.22044605e-16  0.00000000e+00
 -1.11022302e-16  0.00000000e+00  1.38777878e-16  1.11022302e-16
  0.00000000e+00  0.00000000e+00]
